imagePullSecrets:
  # Sostituisci il valore di gatewayfse con il nome del secret che è stato definito
  - name: gatewayfse

secrets:
  #	Nome del key vault definito durante la predisposizione dell'infrastruttura
  keyvaultName: "REPLACE_KEY-VAULT-NAME"
  # ID definito durante la predisposizione dell’infrastruttura
  tenantId: "REPLACE_TENANT-ID"
  secretKeyVaultName: secrets-store-creds

fullnameOverride: it-fse-gtw-govway-manager

govway:
  runService: "it-fse-gtw-govway-run"

# Commentare la seguente sezione se si vuole fare il pull dell'immagine govway dal registry pubblico 
# dei servizi govway
image:
  registry:
    urlGovWay: private-registry/fse
