cloudProvider: azure

imagePullSecrets:
  - name: gatewayfse

secrets:
  mongoDataKeyName: "test"
  azure:
    masterKeyName: "test-master-key"
    keyVaultUrl: "REPLACE_KEY-VAULT-URL"
    keyvaultName: "REPLACE_KEY-VAULT-NAME"
    tenantId: "REPLACE_TENANT-ID"
    secretKeyVaultName: "secrets-store-creds"
    
autoscaler:
  enabled: false 

image:
  registry:
    url: private-registry/fse

env:
  GC_MAX_METASPACE_SIZE: "256"